---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "RootPass123!"
  MYSQL_DATABASE: "three_tier_app"
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "AppPass123!"