---
# overlays/prod/backend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../../base/backend
  - namespace.yaml

images:
  - name: noakhali/todo-backend
    newTag: fe6cc83
    

