---
# overlays/prod/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../../base/frontend
  - namespace.yaml


images:
  - name: noakhali/todo-frontend
    newTag: df109ce
    

