# argocd/apps/dev-mysql.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lovelu99/todo-gitops-repo.git
    targetRevision: main
    path: overlays/dev/mysql
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false                          # ← never auto delete MySQL! data loss risk
      selfHeal: true