---
# overlays/dev/backend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../base/backend
  - namespace.yaml

images:
  - name: noakhali/todo-backend
    newTag: 617317d
    

